services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-go-api:local
    container_name: my-go-api
    ports:
      - "80:8080"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    
  db:
    image: postgres:15-alpine
    container_name: my-go-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data:
